apiVersion: v1
kind: PersistentVolume
metadata:
  name: cantaloupe-data
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /run/desktop/mnt/host/c/kubernetes/idc/cantaloupe-data
    type: DirectoryOrCreate