apiVersion: v1
kind: Service
metadata:
  labels:
    app: drupal-service-local
  name: drupal-service-local
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: drupal