apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../base
  - ../../development/resources/

resources:
  - namespace.yaml
  - activemq-volume.yaml
  - cantaloupe_volume.yaml
  - drupal_pv.yaml
  - etcd-pv.yaml
  - mariadb_pv.yaml
  - solr_pv.yaml

patchesStrategicMerge:
  - mariadb_flush_patch.yaml

  
namespace: windev


  
