apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-data
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /run/desktop/mnt/host/c/kubernetes/idc/mariadb-data
    type: DirectoryOrCreate
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/hostname
  #         operator: In
  #         values:
  #         - docker-desktop    

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-files
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /run/desktop/mnt/host/c/kubernetes/idc/mariadb-dump
    type: DirectoryOrCreate
