apiVersion: v1
kind: PersistentVolume
metadata:
  name: solr-data
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /run/desktop/mnt/host/c/kubernetes/idc/solr
    type: DirectoryOrCreate    
