apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: activemq-data
spec:
  storageClassName: ""
  volumeName: activemq-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
