apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-data
spec:
  storageClassName: ""
  volumeName: etcd-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

