apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../../base
  - ../../base
resources:
  - namespace.yaml
  - resources/
  - volumes/

patchesStrategicMerge:
  - patches/activemq_data_pvc.yaml
  - patches/cantaloupe_data_pvc.yaml
  - patches/drupal_data_pvc.yaml
  - patches/mariadb_files_pvc.yaml
  - patches/solr_data_pvc.yaml
  - patches/drupal-s3-env-patch.yaml
  - patches/drupal-service-patch.yaml
  - patches/drupal.namespace-config-patch.yaml
  - patches/drupal.sp-patch.yaml
  - patches/image-updates-patch.yaml
  - patches/mariadb-deployment-replica-patch.yaml
  - patches/reverseproxy-service-ssl-patch.yaml
  - patches/secret-drupal-root_password-patch.yaml
  - patches/secret-drupal-user_password-patch.yaml ## XXX REMOVE THIS FOR PRODUCTION OR CHANGE THE PASS!!
  - patches/shared-shared-db.host-patch.yaml
  - patches/shared-shared-db.name-patch.yaml
  - patches/shared-shared-db.port-patch.yaml
  - patches/shared-shared-db.rootUser-patch.yaml
  - patches/minio-deployment-patch.yaml

namespace: prod
