apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../../base
  - ../../definitions/resources/


resources:
  - namespace.yaml
  - activemq-volume.yaml
  - cantaloupe_volume.yaml
  - mariadb_pv.yaml
  - etcd-pv.yaml
  - drupal_pv.yaml
  - solr_pv.yaml
  - minio_pv.yaml
  - resources/secrets.yaml
  
patchesStrategicMerge:
   - patches/shared_config-patch.yaml
   - patches/reverseproxy-service-patch.yaml
   - patches/reverseproxy-patch.yaml
namespace: linuxdev
