apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-data
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /minikube-host/idc/drupal
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-codebase
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /minikube-host/idc/drupal-codebase
