apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../base
  - ../../development/resources/

resources:
  - namespace.yaml
  - activemq-volume.yaml
  - cantaloupe_volume.yaml
  - mariadb_pv.yaml
  
namespace: linuxtest

  
