apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-data
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /minikube-host/idc/mariadb-data

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-files
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /minikube-host/idc/mariadb-files
