apiVersion: v1
kind: PersistentVolume
metadata:
  name: activemq-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/idc/activemq-data
    #type: DirectoryOrCreate