apiVersion: v1
kind: PersistentVolume
metadata:
  name: cantaloupe-data
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/idc/cantaloupe-data
    #type: DirectoryOrCreate