apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-data
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp/idc/drupal
    #type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-codebase
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /tmp/idc/drupal-codebase
    #type: DirectoryOrCreate