apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-data
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /tmp/idc/etcd-data
    #type: DirectoryOrCreate    
