apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-data
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/idc/mariadb-data
    type: DirectoryOrCreate
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/hostname
  #         operator: In
  #         values:
  #         - docker-desktop    

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-files
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  #hostPath:
  local:
    path: /tmp/idc/mariadb-dump
    #type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - docker-desktop

