apiVersion: v1
kind: PersistentVolume
metadata:
  name: solr-data
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp/idc/solr
    #type: DirectoryOrCreate    
