apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq
  labels:
    app: activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      containers:
        - image: islandora/activemq:latest
          name: activemq
          imagePullPolicy: Always
          resources:
            requests:
              memory: 500Mi
              cpu: 200m
            limits:
              memory: 1000Mi
          env:
            - name: ACTIVEMQ_USER
              value: client
            - name: ACTIVEMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: activemq
                  key: clientPassword
            - name: ACTIVEMQ_WEB_ADMIN_NAME
              value: admin
            - name: ACTIVEMQ_WEB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: activemq
                  key: adminPassword
            - name: ACTIVEMQ_WEB_ADMIN_ROLES
              value: admin

          
