apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq
  labels:
    app: activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      containers:
        - image: ghcr.io/jhu-idc/activemq:v0.7.7
          name: activemq
          imagePullPolicy: Always
          resources:
            requests:
              memory: 500Mi
              cpu: 200m
            limits:
              memory: 1000Mi
          # XXX: readiness probes do not work for activemq
          # due to the way activemq doesn't open any ports
          # until it can lock the db.
          #    
          # readinessProbe:
          #   tcpSocket:
          #     port: 8161
          #   initialDelaySeconds: 10
          #   periodSeconds: 20
          livenessProbe:
            tcpSocket:
              port: 61616
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: ACTIVEMQ_USER
              value: client
            - name: ACTIVEMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: activemq
                  key: clientPassword
            - name: ACTIVEMQ_WEB_ADMIN_NAME
              value: admin
            - name: ACTIVEMQ_WEB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: activemq
                  key: adminPassword
            - name: ACTIVEMQ_WEB_ADMIN_ROLES
              value: admin
          volumeMounts:
            - mountPath: /opt/activemq/data
              name: activemq-data
          ports:
            - containerPort: 1883
            - containerPort: 5672
            - containerPort: 8161
            - containerPort: 61613
            - containerPort: 61614
            - containerPort: 61616
      volumes:
        - name: activemq-data
          persistentVolumeClaim:
            claimName: activemq-data
          
