apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: activemq-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: efs-sc
  volumeMode: Filesystem
