apiVersion: v1
kind: Service
metadata:
  name: activemq
spec:
  selector:
    app: activemq
  ports:
    - protocol: TCP
      # MQTT
      port: 1886
      name: mqtt
    - protocol: TCP
      # AMPQ
      port: 5672
      name: ampq
    - protocol: TCP
      # WebConsole
      port: 8161
      name: webconsole
    - protocol: TCP
      # STOMP
      port: 61613
      name: stomp
    - protocol: TCP
      # WS
      port: 61614
      name: ws
    - protocol: TCP
      # OpenWire
      port: 61616
      name: openwire
      
      
    
