apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpaca
  name: alpaca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpaca
  template:
    metadata:
      labels:
        app: alpaca
    spec:
      containers:
      - image: ghcr.io/jhu-idc/alpaca:v0.5.0
        name: alpaca
        imagePullPolicy: Always
        resources:
          requests:
            memory: 1000Mi
          limits:
            memory: 2000Mi
        # Alpaca does not open any ports in our stack, probes are not possible.
        # livenessProbe:
        #     httpGet:
        #       path: /health
        #       port: 8080
        #       scheme: HTTP
        #     initialDelaySeconds: 30
        # readinessProbe:     
        #   httpGet:
        #     path: /health
        #     port: 8080
        #     scheme: HTTP
        #   initialDelaySeconds: 20
        env:
          - name: ALPACA_HOMERUS_HTTP_SOCKET_TIMEOUT_MS
            value: "7200"
          - name: ALPACA_ACTIVEMQ_URL
            value: tcp://activemq-service:61616
          - name: ALPACA_ACTIVEMQ_PASSWORD
            value: password
          - name: ALPACA_KARAF_ADMIN_PASSWORD
            value: password
          - name: ALPACA_FITS_SERVICE
            value: http://crayfits-service:8000/
          - name: ALPACA_HOUDINI_SERVICE
            value: http://houdini-service:8000/convert
          - name: ALPACA_HOMARUS_SERVICE
            value: http://homarus-service:8000/convert
          - name: ALPACA_OCR_SERVICE
            value: http://hypercube-service:8000
