apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cantaloupe-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: efs-sc
  volumeMode: Filesystem
  volumeName: cantaloupe-data
