apiVersion: v1
kind: Service
metadata:
  name: cantaloupe-service
  labels:
    app: cantaloupe-service
spec:
  selector:
    app: cantaloupe
  ports:
    - protocol: TCP
      port: 8080
      name: cantaloupe
