apiVersion: apps/v1
kind: Deployment
metadata:
  name: cantaloupe
  labels:
    app: cantaloupe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cantaloupe
  template:
    metadata:
      labels:
        app: cantaloupe
    spec:
      containers:
        - image: ghcr.io/jhu-idc/cantaloupe:v0.7.2
          name: cantaloupe
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /cantaloupe/iiif/2/
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /cantaloupe/iiif/2/
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
          resources:
            requests:
              memory: 400Mi
            limits:
              memory: 2000Mi
          volumeMounts:
            - mountPath: /data
              name: cantaloupe-data
          ports:
            - containerPort: 8080
      volumes:
        - name: cantaloupe-data
          persistentVolumeClaim:
            claimName: cantaloupe-data
