apiVersion: apps/v1
kind: Deployment
metadata:
  name: cantaloupe
  labels:
    app: cantaloupe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cantaloupe
  template:
    metadata:
      labels:
        app: cantaloupe
    spec:
      containers:
        - image: ghcr.io/jhu-sheridan-libraries/idc-isle-dc/cantaloupe:upstream-20200824-f8d1e8e-27-g6cd914d
          name: cantaloupe
          imagePullPolicy: Always
          resources:
            requests:
              memory: 300Mi
            limits:
              memory: 400M
          volumeMounts:
            - mountPath: /data
              name: cantaloupe-data
          ports:
            - containerPort: 8080
      volumes:
        - name: cantaloupe-data
          persistentVolumeClaim:
            claimName: cantaloupe-data
