apiVersion: apps/v1
kind: Deployment
metadata:
  name: crayfits
  labels:
    app: crayfits
spec:
  replicas: 0
  selector:
    matchLabels:
      app: crayfits
  template:
    metadata:
      labels:
        app: crayfits
    spec:
      containers:
        - name: crayfits
          image: ghcr.io/jhu-idc/crayfits:v0.7.2
          imagePullPolicy: Always
          env:
            - name: PHP_MAX_EXECUTION_TIME
              value: "7200"
            - name: NGINX_FASTCGI_READ_TIMEOUT
              value: "7200" 
            - name: NGINX_FASTCGI_SEND_TIMEOUT
              value: "7200" 
            - name: NGINX_FASTCGI_CONNECT_TIMEOUT
              value: "7200" 
            - name: NGINX_PROXY_READ_TIMEOUT
              value: "7200" 
            - name: NGINX_PROXY_SEND_TIMEOUT
              value: "7200" 
            - name: NGINX_PROXY_CONNECT_TIMEOUT
              value: "7200" 
            - name: NGINX_SEND_TIMEOUT
              value: "3600" 
            - name: NGINX_KEEPALIVE_TIMEOUT
              value: "7200" 
            - name: NGINX_CLIENT_BODY_TIMEOUT
              value: "7200" 
            - name: NGINX_LINGERING_TIMEOUT
              value: "7200" 
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
          resources:
            requests:
              memory: 100Mi
            limits:
              memory: 200Mi

