apiVersion: apps/v1
kind: Deployment
metadata:
  name: crayfits
  labels:
    app: crayfits
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crayfits
  template:
    metadata:
      labels:
        app: crayfits
    spec:
      containers:
        - name: crayfits
          image: ghcr.io/jhu-idc/crayfits:v0.2.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: 100Mi
            limits:
              memory: 200Mi

