apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      initContainers:
        - image: ghcr.io/jhu-library-operations/init/wait-for-db:latest
          name: wait-for-db
          imagePullPolicy: Always
          volumeMounts:
            - name: mariadb-files
              mountPath: /var/lib/mysql-files
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: db.host

        - name: init-db
          image: ghcr.io/jhu-library-operations/init/mariadb-init:cda2b04
          imagePullPolicy: Always
          volumeMounts:
            - name: mariadb-files
              mountPath: /var/lib/mysql-files
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: db.host
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: drupal
                  key: root_password
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: db.port
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: db.name
      containers:
        - name: drupal
          #image: ghcr.io/jhu-library-operations/idc/drupal-static:upstream-20201007-739693ae-138-g55f4e3e   
          #image: ghcr.io/jhu-library-operations/drupal-static:upstream-20201007-739693ae-123-g9a3a8e2
          image: ghcr.io/jhu-sheridan-libraries/idc-isle-dc/drupal-static:d593cd5
          imagePullPolicy: Always
          # command: ["/bin/sh"]
          # args: ["-c","while true; do sleep 10; done;"]
          env:
            - name: DRUPAL_DEFAULT_BROKER_HOST
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: activemq.host
            - name: DRUPAL_INSTANCE
              value: static
            - name: DRUPAL_DEFAULT_CONFIGDIR
              value: /var/www/drupal/config/sync
            - name: DRUPAL_DEFAULT_INSTALL_EXISTING_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: drupal.default.install
            - name: DRUPAL_DEFAULT_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: drupal.default.profile
            - name: DRUPAL_DEFAULT_DB_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: db.driver
            - name: DRUPAL_DEFAULT_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: db.host
            - name: DRUPAL_DEFAULT_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: db.port
            - name: DRUPAL_DEFAULT_SALT
              value: 9PPaL0CxZAIcq0l9wxgDGlCZrp7JdT_x7v9gVzpdbUjMt1PqDz3uD0Zy-i16DuJ1-Htuq5hqeg
            - name: DRUPAL_DEFAULT_DB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: drupal
                  key: root_password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: drupal
                  key: root_password
            - name: DRUPAL_DB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: drupal
                  key: root_password
            - name: DRUPAL_DB_ROOT_USER
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: db.rootUser
            - name: DRUPAL_DEFAULT_DB_ROOT_USER
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: db.rootUser
            - name: DRUPAL_DEFAULT_SITE_URL
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: drupal.default.site_url
            - name: DRUPAL_DEFAULT_ACCOUNT_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: drupal.default.email
            - name: DRUPAL_DEFAULT_ACCOUNT_NAME
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: drupal.default.account_name
            - name: DRUPAL_DEFAULT_ACCOUNT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: drupal
                  key: def_acct_pass
            - name: DRUPAL_DEFAULT_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: db.name
            - name: DRUPAL_DEFAULT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: drupal
                  key: user_password
            - name: DRUPAL_DEFAULT_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: drupal.default.db_user
            - name: DEFAULT_SOLR_HOST
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: solr.host
            - name: DRUPAL_DEFAULT_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: drupal.default.email
            - name: DRUPAL_DEFAULT_LOCALE
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: drupal.default.locale
            - name: DRUPAL_DEFAULT_NAME
              value: default
            - name: DRUPAL_DEFAULT_SUBDIR
              value: default
            - name: DRUPAL_DEFAULT_INSTALL
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: drupal.default.install
            - name: BROKER_PORT
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: activemq.port
            - name: CANTALOUPE_URL
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: cantaloupe.url
            - name: SOLR_CORE
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: solr.core
            - name: SOLR_PORT
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: solr.port
            - name: TRIPLESTORE_HOST
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: triplestore.host
            - name: TRIPLESTORE_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: triplestore.namespace
            - name: TRIPLESTORE_PORT
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: triplestore.port
            - name: DRUPAL_SP_SESSION_COOKIENAME
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: drupal.sp.cookiename
            - name: DRUPAL_SP_SESSION_COOKIEPATH
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: drupal.sp.cookiepath
            - name: DRUPAL_SP_SESSION_COOKIESECURE
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: drupal.sp.cookiesecure
            - name: DRUPAL_SP_SESSION_DURATIONSECONDS
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: drupal.sp.session_durationseconds
            - name: DRUPAL_SP_SESSION_DATASTORETIMEOUTSECONDS
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: drupal.sp.session_datastoretimeoutseconds
            - name: DRUPAL_SP_SESSION_STATETIMEOUTSECONDS
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: drupal.sp.session_statetimeoutseconds                  
            - name: DRUPAL_SP_SESSION_COOKIELIFETIMESECONDS
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: drupal.sp.cookielifetime                                    
            - name: DRUPAL_SP_ENTITYID
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: drupal.sp.entityid
            - name: DRUPAL_IDP_ENTITYID
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: drupal.idp.entityid
            - name: DRUPAL_SP_BASEURL
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: drupal.sp.baseurl
            - name: DRUPAL_IDP_BASEURL
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: drupal.idp.baseurl
            - name: DRUPAL_SP_TECHCONTACTEMAIL
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: drupal.sp.techemail
            - name: DRUPAL_SP_TECHCONTACTNAME
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: drupal.sp.techname
            - name: DRUPAL_SP_PROTECTINDEXPAGE 
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: drupal.sp.protectedindexpage
          volumeMounts:
            - name: drupal-data
              mountPath: /var/www/drupal/web/sites/default/files
            - name: saml-secrets
              mountPath: /run/secrets/saml_secrets
              subPath: saml_secrets
            # - name: patchfile
            #   mountPath: /etc/cont-init.d/99-custom-setup.sh
            #   subPath: patchfile
              
      volumes:
        - name: patchfile
          secret:
            secretName: patchfile
            defaultMode: 0755
        - name: drupal-data
          persistentVolumeClaim:
            claimName: drupal-data
        - name: saml-secrets
          secret:
            secretName: saml
            items:
              - key: saml-secrets
                path: saml_secrets
        - name: mariadb-files
          persistentVolumeClaim:
            claimName: mariadb-files
