apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs-sc
  volumeMode: Filesystem
  volumeName: drupal-data
