apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      initContainers:
        - image: ghcr.io/jhu-library-operations/init/wait-for-db:36c5712
          name: wait-for-db
          imagePullPolicy: Always
          volumeMounts:
            - name: mariadb-files
              mountPath: /var/lib/mysql-files
          env:
            - name: MYSQL_HOST
              value: mariadb-service

        - name: init-db
          image: ghcr.io/jhu-library-operations/init/mariadb-init:cda2b04
          imagePullPolicy: Always
          volumeMounts:
            - name: mariadb-files
              mountPath: /var/lib/mysql-files
          env:
            - name: MYSQL_HOST
              value: mariadb-service
            - name: MYSQL_ROOT_PASSWORD
              value: password

      containers:
        - name: drupal
          image: ghcr.io/jhu-library-operations/idc/drupal-static:upstream-20201007-739693ae-138-g55f4e3e   
          #image: ghcr.io/jhu-library-operations/drupal-static:upstream-20201007-739693ae-123-g9a3a8e2
          imagePullPolicy: Always
          env:
            - name: DRUPAL_DEFAULT_BROKER_HOST
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: activemq.host
            - name: DRUPAL_INSTANCE
              value: static
            - name: DRUPAL_DEFAULT_CONFIGDIR
              value: /var/www/drupal/config/sync
            - name: DRUPAL_DEFAULT_INSTALL_EXISTING_CONFIG
              value: "true"
            - name: DRUPAL_DEFAULT_PROFILE
              value: minimal
            - name: DRUPAL_DEFAULT_DB_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: db.driver
            - name: DRUPAL_DEFAULT_DB_HOST
              value: mariadb-service
            - name: DRUPAL_DEFAULT_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: db.port
            - name: DRUPAL_DEFAULT_SALT
              value: 9PPaL0CxZAIcq0l9wxgDGlCZrp7JdT_x7v9gVzpdbUjMt1PqDz3uD0Zy-i16DuJ1-Htuq5hqeg
            - name: DRUPAL_DEFAULT_DB_ROOT_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: DRUPAL_DB_ROOT_PASSWORD
              value: password
            - name: DRUPAL_DB_ROOT_USER
              value: root
            - name: DRUPAL_DEFAULT_DB_ROOT_USER
              value: root
            - name: DRUPAL_DEFAULT_SITE_URL
              value: "http://islandora-idc.traefik.me"
            - name: DRUPAL_DEFAULT_ACCOUNT_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: drupal.default.email
            - name: DRUPAL_DEFAULT_ACCOUNT_NAME
              value: drupal_default
            - name: DRUPAL_DEFAULT_ACCOUNT_PASSWORD
              value: password
            - name: DRUPAL_DEFAULT_DB_NAME
              value: drupal_default
            - name: DRUPAL_DEFAULT_DB_PASSWORD
              value: password
            - name: DRUPAL_DEFAULT_DB_USER
              value: root
            - name: DEFAULT_SOLR_HOST
              value: solr-service
            - name: DRUPAL_DEFAULT_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: drupal.default.email
            - name: DRUPAL_DEFAULT_LOCALE
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: drupal.default.locale
            - name: DRUPAL_DEFAULT_NAME
              value: default
            - name: DRUPAL_DEFAULT_PROFILE
              value: standard
            - name: DRUPAL_DEFAULT_SUBDIR
              value: default
            - name: DRUPAL_DEFAULT_INSTALL
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: drupal.default.install
            - name: BROKER_PORT
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: activemq.port
            - name: CANTALOUPE_URL
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: cantaloupe.url
            - name: SOLR_CORE
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: solr.core
            - name: SOLR_PORT
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: solr.port
            - name: TRIPLESTORE_HOST
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: triplestore.host
            - name: TRIPLESTORE_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: triplestore.namespace
            - name: TRIPLESTORE_PORT
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: triplestore.port
            - name: DRUPAL_SP_SESSION_COOKIENAME
              value: SimpleSAMLSessionID
            - name: DRUPAL_SP_SESSION_COOKIEPATH
              value: "/"
            - name: DRUPAL_SP_SESSION_COOKIESECURE
              value: "false"
            - name: DRUPAL_SP_SESSION_COOKIELIFETIMESECONDS
              value: "0"
            - name: DRUPAL_SP_ENTITYID
              value: https://islandora-idc.traefik.me/sp/shibboleth
            - name: DRUPAL_IDP_ENTITYID
              value: https://islandora-idp.traefik.me/idp/shibboleth
            - name: DRUPAL_SP_BASEURL
              value: https://islandora-idc.traefik.me/
            - name: DRUPAL_IDP_BASEURL
              value: https://islandora-idp.traefik.me/idp/shibboleth
            - name: DRUPAL_SP_TECHCONTACTEMAIL
              value: moo@cow.org
            - name: DRUPAL_SP_TECHCONTACTNAME
              value: Moo Cow
          volumeMounts:
            - name: drupal-data
              mountPath: /var/www/drupal/web/sites/default/files
            - name: saml-secrets
              mountPath: /run/secrets/saml_secrets
              subPath: saml_secrets
            
      volumes:
        - name: drupal-data
          persistentVolumeClaim:
            claimName: drupal-data
        - name: saml-secrets
          secret:
            secretName: saml
            items:
              - key: saml-secrets
                path: saml_secrets
        - name: mariadb-files
          persistentVolumeClaim:
            claimName: mariadb-files
