apiVersion: v1
kind: Service
metadata:
  labels:
    app: drupal-service
  name: drupal-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: drupal
