apiVersion: apps/v1
kind: Deployment
metadata:
  name: fits
  labels:
    app: fits
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fits
  template:
    metadata:
      labels:
        app: fits
    spec:
      containers:
        - name: fits
          image: ghcr.io/jhu-sheridan-libraries/idc-isle-dc/fits:upstream-20200824-f8d1e8e-27-g6cd914d
          resources:
            requests:
              memory: 250Mi
            limits:
              memory: 400Mi          

