apiVersion: apps/v1
kind: Deployment
metadata:
  name: fits
  labels:
    app: fits
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fits
  template:
    metadata:
      labels:
        app: fits
    spec:
      containers:
        - name: fits
          image: ghcr.io/jhu-idc/fits:v0.2.0
          readinessProbe:
            httpGet:
              path: /fits/
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /fits/
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 10
            failureThreshold: 5
          resources:
            requests:
              memory: 250Mi
            limits:
              memory: 400Mi          

