apiVersion: apps/v1
kind: Deployment
metadata:
  name: fits
  labels:
    app: fits
spec:
  replicas: 0
  selector:
    matchLabels:
      app: fits
  template:
    metadata:
      labels:
        app: fits
    spec:
      containers:
        - name: fits
          image: ghcr.io/jhu-idc/fits:v0.6.0
          env:
            - name: PHP_MAX_EXECUTION_TIME
              value: "7200"
            - name: NGINX_FASTCGI_READ_TIMEOUT
              value: "7200" 
            - name: NGINX_FASTCGI_SEND_TIMEOUT
              value: "7200" 
            - name: NGINX_FASTCGI_CONNECT_TIMEOUT
              value: "7200" 
            - name: NGINX_PROXY_READ_TIMEOUT
              value: "7200" 
            - name: NGINX_PROXY_SEND_TIMEOUT
              value: "7200" 
            - name: NGINX_PROXY_CONNECT_TIMEOUT
              value: "7200" 
            - name: NGINX_SEND_TIMEOUT
              value: "3600" 
            - name: NGINX_KEEPALIVE_TIMEOUT
              value: "7200" 
            - name: NGINX_CLIENT_BODY_TIMEOUT
              value: "7200" 
            - name: NGINX_LINGERING_TIMEOUT
              value: "7200"            
          readinessProbe:
            httpGet:
              path: /fits/
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /fits/
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 10
            failureThreshold: 5
          resources:
            requests:
              memory: 1000Mi
            limits:
              memory: 2000Mi          

