apiVersion: apps/v1
kind: Deployment
metadata:
  name: fits
  labels:
    app: fits
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fits
  template:
    metadata:
      labels:
        app: fits
    spec:
      containers:
        - name: fits
          image: ghcr.io/jhu-sheridan-libraries/idc-isle-dc/fits:upstream-20200824-f8d1e8e-46-gf9beba1
          resources:
            requests:
              memory: 1000Mi
            limits:
              memory: 2000Mi          

