apiVersion: apps/v1
kind: Deployment
metadata:
  name: homarus
  labels:
    app: homarus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homarus
  template:
    metadata:
      labels:
        app: homarus
    spec:
      containers:
        - name: homarus
          image: ghcr.io/jhu-idc/homarus:v0.7.4
          imagePullPolicy: Always
          
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: 1000Mi
            limits:
              memory: 2000Mi          
          env:
            - name: HOMARUS_JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: drupal-sealed
                  key: jwt_public_key
            - name: HOMARUS_JWT_ADMIN_TOKEN
              value: islandora
            - name: PHP_MAX_EXECUTION_TIME
              value: "7200"
            - name: NGINX_FASTCGI_READ_TIMEOUT
              value: "7200" 
            - name: NGINX_FASTCGI_SEND_TIMEOUT
              value: "7200" 
            - name: NGINX_FASTCGI_CONNECT_TIMEOUT
              value: "7200" 
            - name: NGINX_PROXY_READ_TIMEOUT
              value: "7200" 
            - name: NGINX_PROXY_SEND_TIMEOUT
              value: "7200" 
            - name: NGINX_PROXY_CONNECT_TIMEOUT
              value: "7200" 
            - name: NGINX_SEND_TIMEOUT
              value: "3600" 
            - name: NGINX_KEEPALIVE_TIMEOUT
              value: "7200" 
            - name: NGINX_CLIENT_BODY_TIMEOUT
              value: "7200" 
            - name: NGINX_LINGERING_TIMEOUT
              value: "7200"
