apiVersion: apps/v1
kind: Deployment
metadata:
  name: homarus
  labels:
    app: homarus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homarus
  template:
    metadata:
      labels:
        app: homarus
    spec:
      containers:
        - name: homarus
          image: ghcr.io/jhu-idc/homarus:v0.2.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: 100Mi
            limits:
              memory: 200Mi          
          env:
            - name: HOMARUS_JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: drupal-sealed
                  key: jwt_public_key
            - name: HOMARUS_JWT_ADMIN_TOKEN
              value: islandora
