apiVersion: v1
kind: Service
metadata:
  name: houdini-service
  labels:
    app: houdini-service
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: houdini
  
