apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: houdini
  name: houdini
spec:
  replicas: 1
  selector:
    matchLabels:
      app: houdini
  template:
    metadata:
      labels:
        app: houdini
    spec:
      containers:
        - name: houdini
          image: ghcr.io/jhu-idc/houdini:v0.7.20
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: 2500Mi
            limits:
              memory: 2500Mi
          env:
            - name: PHP_MAX_EXECUTION_TIME
              value: "7200"
            - name: NGINX_FASTCGI_READ_TIMEOUT
              value: "7200" 
            - name: NGINX_FASTCGI_SEND_TIMEOUT
              value: "7200" 
            - name: NGINX_FASTCGI_CONNECT_TIMEOUT
              value: "7200" 
            - name: NGINX_PROXY_READ_TIMEOUT
              value: "7200" 
            - name: NGINX_PROXY_SEND_TIMEOUT
              value: "7200" 
            - name: NGINX_PROXY_CONNECT_TIMEOUT
              value: "7200" 
            - name: NGINX_SEND_TIMEOUT
              value: "3600" 
            - name: NGINX_KEEPALIVE_TIMEOUT
              value: "7200" 
            - name: NGINX_CLIENT_BODY_TIMEOUT
              value: "7200" 
            - name: NGINX_LINGERING_TIMEOUT
              value: "7200"              
            - name: HOUDINI_JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: drupal-sealed
                  key: jwt_public_key
            - name: HOUDINI_JWT_ADMIN_TOKEN
              value: islandora
  
