apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: houdini
  name: houdini
spec:
  replicas: 1
  selector:
    matchLabels:
      app: houdini
  template:
    metadata:
      labels:
        app: houdini
    spec:
      containers:
        - name: houdini
          image: ghcr.io/jhu-sheridan-libraries/idc-isle-dc/houdini:upstream-20200824-f8d1e8e-54-g93a2b68
          resources:
            requests:
              memory: 100Mi
            limits:
              memory: 200Mi
          env:
            - name: HOUDINI_JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: drupal-sealed
                  key: jwt_public_key
            - name: HOUDINI_JWT_ADMIN_TOKEN
              value: islandora
  
