apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hypercube
  name: hypercube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hypercube
  template:
    metadata:
      labels:
        app: hypercube
    spec:
      containers:
      - image: ghcr.io/jhu-sheridan-libraries/idc-isle-dc/hypercube:upstream-20200824-f8d1e8e-27-g6cd914d
        name: hypercube
        resources:
          requests:
            memory: 100Mi
          limits:
            memory: 200Mi  
        env:
          - name: HYPERCUBE_JWT_PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                name: drupal-sealed
                key: jwt_public_key
          - name: HYPERCUBE_JWT_ADMIN
            value: islandora
