apiVersion: v1
kind: Service
metadata:
  name: hypercube-service
  labels:
    app: hypercube-service
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: hypercube
