apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hypercube
  name: hypercube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hypercube
  template:
    metadata:
      labels:
        app: hypercube
    spec:
      containers:
      - image: ghcr.io/jhu-idc/hypercube:v0.7.4
        name: hypercube
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 20
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20        
        resources:
          requests:
            memory: 6656Mi
          limits:
            memory: 6656Mi  
        env:
          - name: PHP_MAX_EXECUTION_TIME
            value: "7200"
          - name: NGINX_FASTCGI_READ_TIMEOUT
            value: "7200" 
          - name: NGINX_FASTCGI_SEND_TIMEOUT
            value: "7200" 
          - name: NGINX_FASTCGI_CONNECT_TIMEOUT
            value: "7200" 
          - name: NGINX_PROXY_READ_TIMEOUT
            value: "7200" 
          - name: NGINX_PROXY_SEND_TIMEOUT
            value: "7200" 
          - name: NGINX_PROXY_CONNECT_TIMEOUT
            value: "7200" 
          - name: NGINX_SEND_TIMEOUT
            value: "3600" 
          - name: NGINX_KEEPALIVE_TIMEOUT
            value: "7200" 
          - name: NGINX_CLIENT_BODY_TIMEOUT
            value: "7200" 
          - name: NGINX_LINGERING_TIMEOUT
            value: "7200"            
          - name: HYPERCUBE_JWT_PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                name: drupal-sealed
                key: jwt_public_key
          - name: HYPERCUBE_JWT_ADMIN
            value: islandora
