apiVersion: apps/v1
kind: Deployment
metadata:
  name: idp
  labels:
    app: idp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idp
  template:
    metadata:
      labels:
        app: idp
    spec:
      containers:
        - name: idp
          image: ghcr.io/jhu-library-operations/idc/idp:upstream-20200824-f8d1e8e-19-g78fcf0f.dirty
          #image: ghcr.io/jhu-sheridan-libraries/idc-isle-dc/idp:upstream-20200824-f8d1e8e-14-g09641e3
          imagePullPolicy: Always
          env:
            - name: IDP_BASEURL
              value: https://islandora-idp.traefik.me:4443
            - name: IDP_ENTITYID
              value: https://islandora-idp.traefik.me/idp/shibboleth
            - name: JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD
              value: password
            - name: JETTY_MAX_HEAP
              value: 64m
            - name: SP_BASEURL
              value: https://islandora-idc.traefik.me
            - name: SP_ENTITYID
              value: https://islandora-idc.traefik.me/sp/shibboleth
            - name: JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD
              value: password
            - name: JETTY_BROWSER_SSL_KEYSTORE_PASSWORD
              value: password
          volumeMounts:
            - name: idp-sealer
              mountPath: /run/secrets/idp_sealer
              subPath: idp_sealer
            - name: idp-backchannel
              mountPath: /run/secrets/idp_backchannel
              subPath: idp_backchannel
            - name: idp-browser
              mountPath: /run/secrets/idp_browser
              subPath: idp_browser
            - name: saml-secrets
              mountPath: /run/secrets/saml_secrets
              subPath: saml_secrets
      volumes:
        - name: idp-sealer
          secret:
            secretName: idp
            items:
              - key: sealer.jks
                path: idp_sealer
        - name: idp-backchannel
          secret:
            secretName: idp
            items:
              - key: idp-backchannel.p12
                path: idp_backchannel
        - name: idp-browser
          secret:
            secretName: idp
            items:
              - key: idp-browser.p12
                path: idp_browser
        - name: saml-secrets
          secret:
            secretName: saml
            items:
              - key: saml-secrets
                path: saml_secrets

