apiVersion: apps/v1
kind: Deployment
metadata:
  name: idp
  labels:
    app: idp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idp
  template:
    metadata:
      labels:
        app: idp
    spec:
      containers:
        - name: idp
          image: ghcr.io/jhu-sheridan-libraries/idc-isle-dc/idp:upstream-20200824-f8d1e8e-14-g09641e3
          imagePullPolicy: Always
          env:
            - name: IDP_BASEURL
              value: https://islandora-idp.traefik.me:4443
            - name: IDP_ENTITYID
              value: https://islandora-idp.traefik.me/idp/shibboleth
            - name: JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD
              value: password
            - name: JETTY_MAX_HEAP
              value: 64m
            - name: SP_BASEURL
              value: https://islandora-idc.traefik.me
            - name: SP_ENTITYID
              value: https://islandora-idc.traefik.me/sp/shibboleth
          
