apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - activemq_deployment.yaml
  - activemq_service.yaml
  - alpaca_deployment.yaml
  - cantaloupe_deployment.yaml
  - cantaloupe_service.yaml
  - mariadb_service.yaml
  - mariadb_deployment.yaml
  - drupal_deployment.yaml
#  - drupal_configmap.yaml
  - shared_configmap.yaml
  - fits_deployment.yaml
  - homarus_deployment.yaml
  - houdini_deployment.yaml
