apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-files
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: efs-sc
  volumeMode: Filesystem
  volumeName: mariadb-files
