apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  labels:
    app: mariadb-service
spec:
  selector:
    app: mariadb
  clusterIP: "None"
  ports:
    - protocol: TCP
      port: 3306
      name: mysql

