apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - image: ghcr.io/jhu-idc/mariadb:v0.2.0
          name: mariadb
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb-data
            - mountPath: /var/lib/mysql-files
              name: mariadb-files
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: drupal
                  key: root_password
          resources:
            requests:
              memory: "512Mi"
              cpu: 0.5
      initContainers:
        - image: ghcr.io/jhu-idc/mariadb/perms-init-container:latest
          name: mariadb-init-data-perms
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb-data
            - mountPath: /var/lib/mysql-files
              name: mariadb-files
          env:
            - name: MARIADB_INIT_DIRECTORY
              value: /var/lib/mysql
            - name: MARIADB_CHANGE_TO
              value: "100:101"

      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-data
        - name: mariadb-files
          persistentVolumeClaim:
            claimName: mariadb-files
