apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      initContainers:
        - name: create-bucket-dir
          image: alpine:latest
          command: ["/bin/sh"]
          args: ["-c", "mkdir -p /data/$MINIO_INITIAL_BUCKET"] 
          env:
            - name: MINIO_INITIAL_BUCKET
              valueFrom: 
                secretKeyRef:
                  name: drupal
                  key: s3BucketName
          volumeMounts:
            - mountPath: /data
              name: minio-data
      containers:
        - name: minio
          image: minio/minio:RELEASE.2020-08-26T00-00-49Z
          # command: ["./minio"]
          args: ["server", "/data"]
          imagePullPolicy: Always
        # NEED VOLUMES
          volumeMounts:
            - mountPath: /data
              name: minio-data
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: drupal
                  key: s3AccessKey            
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: drupal
                  key: s3SecretKey

      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-data