apiVersion: v1
kind: Service
metadata:
  name: reverseproxy-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 4015
    - port: 443
      name: https
      protocol: TCP
      targetPort: 80
  selector:
    app: reverseproxy