apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solr
  name: solr
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: solr
  template:
    metadata:
      labels:
        app: solr
    spec:
      containers:
      - image: ghcr.io/jhu-idc/solr:v0.7.4
        name: solr
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /solr/
            port: 8983
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /solr/
            port: 8983
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 5        
        resources:
            requests:
              memory: 4096Mi
            limits:
              memory: 8192Mi  
        volumeMounts:
          - mountPath: /opt/solr/server/solr
            name: solr-data
        env:
          - name: CONFD_LOG_LEVEL
            value: debug
      volumes:
        - name: solr-data
          persistentVolumeClaim:
            claimName: solr-data
