apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solr
  name: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solr
  template:
    metadata:
      labels:
        app: solr
    spec:
      containers:
#      - image: ghcr.io/jhu-sheridan-libraries/idc-isle-dc/solr:upstream-20200824-f8d1e8e-14-g09641e3
      - image: ghcr.io/jhu-library-operations/solr:upstream-20200824-f8d1e8e-19-g5c591a1.dirty
        name: solr
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /opt/solr/server/solr
            name: solr-data
        env:
          - name: CONFD_LOG_LEVEL
            value: debug
      volumes:
        - name: solr-data
          persistentVolumeClaim:
            claimName: solr-data
