apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solr
  name: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solr
  template:
    metadata:
      labels:
        app: solr
    spec:
      containers:
      - image: ghcr.io/jhu-idc/solr:v0.2.0
        name: solr
        imagePullPolicy: Always
        resources:
            requests:
              memory: 800Mi
            limits:
              memory: 1024Mi  
        volumeMounts:
          - mountPath: /opt/solr/server/solr
            name: solr-data
        env:
          - name: CONFD_LOG_LEVEL
            value: debug
      volumes:
        - name: solr-data
          persistentVolumeClaim:
            claimName: solr-data
