apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-data
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /run/desktop/mnt/host/c/kubernetes/idc/etcd-data
    type: DirectoryOrCreate    
