apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-data
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /run/desktop/mnt/host/c/kubernetes/idc/minio/
    