apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cantaloupe-data
spec:
  storageClassName: ""
  volumeName: cantaloupe-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
