apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
spec:
  storageClassName: ""
  volumeName: minio-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
