name: Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  kubernetes_test:
    name: kube-tools
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: kustomize
        uses: jhu-library-operations/kube-tools
        with:
          kustomize: 3.8.7
          command: |
            kustomize build overlays/aws/test
  
      
